// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Willen LLC

package phantom.core.transport

import com.ionspin.kotlin.crypto.LibsodiumInitializer
import com.ionspin.kotlin.crypto.auth.Auth
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFails
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Trek 2 Stage 2B-B (C1) — unit tests for [SeqMacVerifier].
 *
 * Covers test cells:
 *
 *   * **M8** — golden-vector parity against `services/relay/tests/seq_mac_vectors.rs`.
 *     The Rust file asserts determinism + cross-input distinctness for 13
 *     named vectors without byte-pinning hex output. The Kotlin side
 *     mirrors the same 13 input shapes here under the same property
 *     pattern: same `(identity, seq, envelope_id, sequence_ts, key)`
 *     reliably produces the same MAC; any single-input change produces a
 *     distinct MAC. Both sides share one canonical encoding spec; any
 *     drift breaks both test suites simultaneously.
 *
 *   * **M9** — single happy-path verify success against a known fixed
 *     `(key, identity, seq, envelope_id, sequence_ts)` tuple, asserting
 *     [SeqMacVerifier.Outcome.Verified] when the MAC is the wire-encoded
 *     output of [SeqMacVerifier.computeMac] for the same tuple.
 *     Determinism: two consecutive verify calls with identical inputs
 *     reach the same outcome.
 *
 *   * **M-B7** — independent Rust-generated multi-byte UTF-8 golden
 *     vector. Pin lives at `services/relay/tests/seq_mac_vectors.rs`
 *     test `vector_mb7_multi_byte_utf8_oracle_pin`. The hex below is
 *     a byte-pinned oracle generated by the Rust test; a Kotlin
 *     drift produces a hex mismatch HERE; a Rust drift produces a
 *     hex mismatch in the Rust test. Two-sided lock.
 *
 *   * **M-B9** — hex-key-decode-before-use guard. Computing the MAC
 *     with the raw 32-byte verify-key bytes produces a value that
 *     verifies; computing it with the 64-byte ASCII hex string treated
 *     as bytes produces a DIFFERENT value that does NOT verify. Pins
 *     the load-bearing decode step in [SeqMacVerifier.verify].
 *
 * Tests run under `runTest { init(); ... }` to gate `LibsodiumInitializer`
 * once per case (the call is idempotent).
 */
class SeqMacVerifierTest {

    private suspend fun init() {
        if (!LibsodiumInitializer.isInitialized()) {
            LibsodiumInitializer.initialize()
        }
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    /** All-`a` 64-char identity hex mirroring `seq_mac_vectors.rs`'s `all_a_identity`. */
    private val ALL_A_IDENTITY: String = "a".repeat(64)

    /** All-`f` 64-char identity hex (vector 2 corner). */
    private val ALL_F_IDENTITY: String = "f".repeat(64)

    /** All-`c` 64-char identity hex (vector 4 corner). */
    private val ALL_C_IDENTITY: String = "c".repeat(64)

    /** `a1` × 32 = realistic mid-range identity (vector 3 corner). */
    private val MID_RANGE_IDENTITY: String = "a1".repeat(32)

    /** Lower-cased hex projection of a [ByteArray]. */
    private fun ByteArray.toLowerHex(): String =
        joinToString("") { byte -> "%02x".format(byte.toInt() and 0xFF) }

    /**
     * Derive the per-identity verify key the same way the relay does at
     * `SeqMacRootKey::derive_verify_key`:
     *
     *   verify_key = HMAC-SHA-256(root_key, b"phantom-seq-mac-key-v1\x00" || identity_hex)
     *
     * Exposed here so the test fixture can mirror the server-side
     * derivation without importing the production relay code.
     */
    @OptIn(ExperimentalUnsignedTypes::class)
    private fun deriveVerifyKey(rootKey: ByteArray, identityHex: String): ByteArray {
        val keyDomainTag = "phantom-seq-mac-key-v1".encodeToByteArray() + byteArrayOf(0)
        val msg = keyDomainTag + identityHex.encodeToByteArray()
        return Auth.authHmacSha256(
            message = msg.toUByteArray(),
            key = rootKey.toUByteArray(),
        ).toByteArray()
    }

    private fun zeroRoot(): ByteArray = ByteArray(32)

    // ── M9 — verify happy path ────────────────────────────────────────────────

    @Test
    fun verify_returns_Verified_on_canonical_round_trip() = runTest {
        init()
        val verifyKey = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val verifyKeyHex = verifyKey.toLowerHex()

        val computedMac = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "00000000-0000-0000-0000-000000000000",
            sequenceTs = 0L,
            verifyKeyBytes = verifyKey,
        )
        val seqMacHex = computedMac.toLowerHex()

        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "00000000-0000-0000-0000-000000000000",
            sequenceTs = 0L,
            seqMacHex = seqMacHex,
            verifyKeyHex = verifyKeyHex,
        )
        assertEquals(SeqMacVerifier.Outcome.Verified, outcome)
    }

    @Test
    fun verify_is_deterministic_for_identical_inputs() = runTest {
        init()
        val verifyKey = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val verifyKeyHex = verifyKey.toLowerHex()
        val envelopeId = "0123456789abcdef0123456789abcdef"

        val computedMac = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = envelopeId,
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = verifyKey,
        )
        val seqMacHex = computedMac.toLowerHex()

        val outcomeA = SeqMacVerifier.verify(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = envelopeId,
            sequenceTs = 1_700_000_000_000L,
            seqMacHex = seqMacHex,
            verifyKeyHex = verifyKeyHex,
        )
        val outcomeB = SeqMacVerifier.verify(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = envelopeId,
            sequenceTs = 1_700_000_000_000L,
            seqMacHex = seqMacHex,
            verifyKeyHex = verifyKeyHex,
        )
        assertEquals(SeqMacVerifier.Outcome.Verified, outcomeA)
        assertEquals(SeqMacVerifier.Outcome.Verified, outcomeB)
    }

    // ── M8 — golden-vector parity (mirroring seq_mac_vectors.rs) ──────────────

    @Test
    fun vector_1_all_zero_inputs_round_trips() = runTest {
        // Mirrors Rust `vector_1_all_zero_inputs_round_trips`.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val macA = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "00000000-0000-0000-0000-000000000000",
            sequenceTs = 0L,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "00000000-0000-0000-0000-000000000000",
            sequenceTs = 0L,
            verifyKeyBytes = key,
        )
        assertContentByteEquals(macA, macB, "vector 1 must be deterministic")
        assertEquals(SeqMacVerifier.SEQ_MAC_RAW_LENGTH, macA.size)
    }

    @Test
    fun vector_2_all_ones_inputs_round_trips() = runTest {
        // Mirrors Rust `vector_2_all_ones_inputs_round_trips`. Largest
        // representable u64 corners. `u64::MAX - (u64::MAX % 60_000)`
        // collapses to `Long.MAX_VALUE - (Long.MAX_VALUE % 60_000)` for
        // the high half of the bit space because the encoding routes
        // through unsigned BE bytes — the high bit is preserved on the
        // wire. See SeqMacVerifier.writeU64BigEndian.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_F_IDENTITY)
        // `Long.MAX_VALUE` covers all non-sign bits set; for the u64::MAX
        // analogue the encoding produces `7fffffffffffffff` BE in the
        // signed Long representation. The Rust side uses `u64::MAX` which
        // is `0xffff_ffff_ffff_ffff`. To exercise the high-bit position
        // we also test `-1L` (all bits set in Long, encodes to
        // `0xffff_ffff_ffff_ffff` BE — the same bytes as Rust's `u64::MAX`).
        val seqMax = -1L
        val tsRaw = -1L
        val tsPostQuantize = tsRaw - (tsRaw.mod(60_000L)) // negative mod handles Long sign
        val macA = SeqMacVerifier.computeMac(
            identityHex = ALL_F_IDENTITY,
            seq = seqMax,
            envelopeId = "ffffffff-ffff-ffff-ffff-ffffffffffff",
            sequenceTs = tsPostQuantize,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = ALL_F_IDENTITY,
            seq = seqMax,
            envelopeId = "ffffffff-ffff-ffff-ffff-ffffffffffff",
            sequenceTs = tsPostQuantize,
            verifyKeyBytes = key,
        )
        assertContentByteEquals(macA, macB, "vector 2 must be deterministic")
    }

    @Test
    fun vector_3_realistic_mid_range_inputs_round_trips() = runTest {
        // Mirrors Rust `vector_3_realistic_mid_range_inputs_round_trips`.
        init()
        val key = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val envelopeId = "0123456789abcdef0123456789abcdef"
        val macA = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = envelopeId,
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = envelopeId,
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        assertContentByteEquals(macA, macB)
    }

    @Test
    fun vector_4_quantization_boundary_pre_vs_post_produces_different_macs() = runTest {
        // Mirrors Rust `vector_4_quantization_boundary_canary_pre_vs_post_produces_different_macs`.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_C_IDENTITY)
        val macPre = SeqMacVerifier.computeMac(
            identityHex = ALL_C_IDENTITY,
            seq = 1L,
            envelopeId = "envelope-id",
            sequenceTs = 1_700_000_000_001L,
            verifyKeyBytes = key,
        )
        val macPost = SeqMacVerifier.computeMac(
            identityHex = ALL_C_IDENTITY,
            seq = 1L,
            envelopeId = "envelope-id",
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        assertContentByteNotEquals(macPre, macPost)
    }

    @Test
    fun vector_5_drift_detector_different_envelope_id_changes_mac() = runTest {
        // Mirrors Rust `vector_5_drift_detector_different_envelope_id_changes_mac`.
        init()
        val key = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val macA = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = "0123456789abcdef0123456789abcdef",
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1_234L,
            envelopeId = "fedcba9876543210fedcba9876543210",
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        assertContentByteNotEquals(macA, macB)
    }

    @Test
    fun boundary_empty_envelope_id_does_not_throw() = runTest {
        // Mirrors Rust `boundary_empty_envelope_id_does_not_panic`. Empty
        // envelope_id produces a 101-byte canonical input (no envelope_id
        // bytes between the u16 length-prefix `0x00 0x00` and `sequence_ts`).
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val mac = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 1L,
            envelopeId = "",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        assertEquals(SeqMacVerifier.SEQ_MAC_RAW_LENGTH, mac.size)
    }

    @Test
    fun boundary_envelope_id_at_u16_max_accepted() = runTest {
        // Mirrors Rust `boundary_envelope_id_at_u16_max_accepted_one_over_rejected`
        // (the accepted half — the rejected half is enforced via the verify
        // path's `ENVELOPE_ID_MAX_BYTES` check, not the computeMac path).
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val atLimit = "x".repeat(SeqMacVerifier.ENVELOPE_ID_MAX_BYTES)
        val mac = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 1L,
            envelopeId = atLimit,
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        assertEquals(SeqMacVerifier.SEQ_MAC_RAW_LENGTH, mac.size)
    }

    @Test
    fun boundary_envelope_id_one_over_u16_max_via_verify_path_returns_MalformedSeqMac() = runTest {
        // Verify path defensively rejects over-cap envelope ids because
        // a hostile or buggy caller might construct one. The server
        // contract enforces the cap at the request boundary; this
        // assertion holds the defence-in-depth property.
        init()
        val verifyKey = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val verifyKeyHex = verifyKey.toLowerHex()
        val oneOver = "x".repeat(SeqMacVerifier.ENVELOPE_ID_MAX_BYTES + 1)
        // Provide a syntactically-valid 64-char hex seqMac so the
        // MalformedSeqMac outcome is driven by the envelope_id size,
        // not the seq_mac shape.
        val syntacticallyValidSeqMacHex = "0".repeat(64)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 1L,
            envelopeId = oneOver,
            sequenceTs = 60_000L,
            seqMacHex = syntacticallyValidSeqMacHex,
            verifyKeyHex = verifyKeyHex,
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    // ── Determinism + cross-input distinctness (M8 spec property tests) ──────

    @Test
    fun verify_key_derivation_is_deterministic_for_zero_root() = runTest {
        // Mirrors Rust `derive_verify_key_is_deterministic_for_zero_root`.
        init()
        val keyA = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val keyB = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        assertContentByteEquals(keyA, keyB)
        assertEquals(32, keyA.size, "verify key must be 32 bytes")
        assertEquals(64, keyA.toLowerHex().length)
    }

    @Test
    fun verify_key_derivation_differs_per_identity() = runTest {
        // Mirrors Rust `derive_verify_key_differs_per_identity`.
        init()
        val keyA = deriveVerifyKey(zeroRoot(), "a".repeat(64))
        val keyB = deriveVerifyKey(zeroRoot(), "b".repeat(64))
        assertContentByteNotEquals(keyA, keyB)
    }

    @Test
    fun mac_differs_for_off_by_one_seq() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val macA = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 100L,
            envelopeId = "abc",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 101L,
            envelopeId = "abc",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        assertContentByteNotEquals(macA, macB)
    }

    @Test
    fun mac_differs_for_single_bit_flipped_identity_hex() = runTest {
        init()
        // Flip a single character in the identity to flip a single
        // 4-bit nibble in the ASCII representation.
        val idA = "a".repeat(64)
        val idB = "b" + "a".repeat(63)
        val keyA = deriveVerifyKey(zeroRoot(), idA)
        val keyB = deriveVerifyKey(zeroRoot(), idB)
        val macA = SeqMacVerifier.computeMac(
            identityHex = idA,
            seq = 1L,
            envelopeId = "abc",
            sequenceTs = 60_000L,
            verifyKeyBytes = keyA,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = idB,
            seq = 1L,
            envelopeId = "abc",
            sequenceTs = 60_000L,
            verifyKeyBytes = keyB,
        )
        assertContentByteNotEquals(macA, macB)
    }

    @Test
    fun mac_differs_for_single_char_changed_envelope_id() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val macA = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeId = "envelope-id-a",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        val macB = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeId = "envelope-id-b",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        assertContentByteNotEquals(macA, macB)
    }

    // ── M-B7 — multi-byte UTF-8 envelope_id parity ──────────────────────────

    @Test
    fun mb7_multi_byte_utf8_envelope_id_byte_length_distinct_from_ascii() = runTest {
        // Mirrors Rust `boundary_multi_byte_utf8_envelope_id_is_encoded_by_byte_length`.
        // `Ω` is 2 UTF-8 bytes; `x` is 1 UTF-8 byte. Two envelope_ids of
        // identical char count but different UTF-8 byte length MUST hash
        // distinctly (the byte length is committed via the u16-BE length
        // prefix). A regression that used `String.length` instead of
        // `encodeToByteArray().size` would produce the same length prefix
        // for both inputs but different envelope_id_bytes content, still
        // producing distinct MACs — so this test alone is not sufficient
        // to catch the regression. See the byte-pinned oracle test
        // [mb7_multi_byte_utf8_byte_pinned_oracle_matches_rust] below
        // for the load-bearing parity assertion.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val macOmega = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 1L,
            envelopeId = "Ω", // Greek capital omega — 2 UTF-8 bytes (0xCE 0xA9)
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        val macX = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 1L,
            envelopeId = "x",
            sequenceTs = 60_000L,
            verifyKeyBytes = key,
        )
        assertContentByteNotEquals(macOmega, macX)
    }

    @Test
    fun mb7_multi_byte_utf8_byte_pinned_oracle_matches_rust() = runTest {
        // Pinned hex value generated INDEPENDENTLY on the Rust side at
        // `services/relay/tests/seq_mac_vectors.rs::vector_mb7_multi_byte_utf8_oracle_pin`.
        // Inputs are:
        //
        //   root_key      = [0u8; 32]
        //   identity_hex  = "a" × 64                              (ALL_A_IDENTITY)
        //   verify_key    = derive_verify_key(root_key, identity)
        //   seq           = 42
        //   envelope_id   = "Ω"        (Greek capital omega, 2 UTF-8 bytes)
        //   sequence_ts   = 1_700_000_000_000  (post-quantize)
        //
        // A drift in the canonical encoding on EITHER side produces a
        // hex mismatch HERE and on the matching Rust test. The Rust
        // test pins the hex byte-for-byte; a Kotlin change without a
        // matching Rust change must update both files together.
        //
        // Hex captured by running the Rust oracle and pasting the
        // observed value verbatim. Re-generate by editing the matching
        // Rust test to `assert_eq!(hex, "FAILME")` and reading the
        // panic message.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val mac = SeqMacVerifier.computeMac(
            identityHex = ALL_A_IDENTITY,
            seq = 42L,
            envelopeId = "Ω",
            sequenceTs = 1_700_000_000_000L,
            verifyKeyBytes = key,
        )
        val rustOracleHex = "9173956a76ba212e35989fee7768defd962c5fdff610b12ba5c584adda2af3dd"
        assertEquals(
            rustOracleHex,
            mac.toLowerHex(),
            "M-B7 oracle drift: Kotlin computed ${mac.toLowerHex()} but Rust pin is $rustOracleHex. " +
                "If both sides changed together, update the pin on BOTH files.",
        )
    }

    // ── M-B9 — hex-key-decode-before-use ────────────────────────────────────

    @Test
    fun mb9_mac_with_raw_key_bytes_verifies_mac_with_ascii_hex_key_does_not() = runTest {
        // Load-bearing: the HMAC key MUST be the raw 32 verify-key bytes,
        // NOT the 64-byte ASCII hex string. A regression that passed the
        // hex `String` as the HMAC key would produce a different MAC
        // value, and the verify path would silently report MacMismatch
        // on every server-generated envelope. This test pins the
        // difference explicitly.
        init()
        val verifyKey = deriveVerifyKey(zeroRoot(), MID_RANGE_IDENTITY)
        val verifyKeyHex = verifyKey.toLowerHex()
        val envelopeId = "abc"

        // MAC computed with the RAW 32-byte key — what the production
        // SeqMacVerifier does.
        val macWithRawKey = SeqMacVerifier.computeMac(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeId = envelopeId,
            sequenceTs = 60_000L,
            verifyKeyBytes = verifyKey,
        )

        // MAC computed with the 64-byte ASCII hex string as the HMAC key
        // — the regression value.
        @OptIn(ExperimentalUnsignedTypes::class)
        val canonicalInput = SeqMacVerifier.buildCanonicalInput(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeIdBytes = envelopeId.encodeToByteArray(),
            sequenceTs = 60_000L,
        )
        @OptIn(ExperimentalUnsignedTypes::class)
        val macWithHexAsciiKey = Auth.authHmacSha256(
            message = canonicalInput.toUByteArray(),
            key = verifyKeyHex.encodeToByteArray().toUByteArray(),
        ).toByteArray()

        // The two MACs must differ. A regression where the verifier
        // accidentally passed the hex string as the HMAC key would
        // produce `macWithHexAsciiKey` and silently fail every verify.
        assertContentByteNotEquals(
            macWithRawKey,
            macWithHexAsciiKey,
            "raw-key MAC must differ from ASCII-hex-key MAC; otherwise the " +
                "load-bearing hex-decode-before-use step is not exercised",
        )

        // And: verifier called with the correctly-encoded
        // (raw-key-derived) `seqMacHex` returns Verified.
        val outcomeMatch = SeqMacVerifier.verify(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeId = envelopeId,
            sequenceTs = 60_000L,
            seqMacHex = macWithRawKey.toLowerHex(),
            verifyKeyHex = verifyKeyHex,
        )
        assertEquals(SeqMacVerifier.Outcome.Verified, outcomeMatch)

        // And: verifier called with the regression-MAC (computed with
        // ASCII-hex-bytes-as-key) returns MacMismatch — the verifier
        // re-runs the canonical input through `hexDecode(verifyKeyHex)`
        // and so produces a different HMAC than the attacker / bug
        // produced with the ASCII bytes.
        val outcomeMismatch = SeqMacVerifier.verify(
            identityHex = MID_RANGE_IDENTITY,
            seq = 1L,
            envelopeId = envelopeId,
            sequenceTs = 60_000L,
            seqMacHex = macWithHexAsciiKey.toLowerHex(),
            verifyKeyHex = verifyKeyHex,
        )
        assertEquals(SeqMacVerifier.Outcome.MacMismatch, outcomeMismatch)
    }

    // ── Malformed-input handling (feeds C4 / M-B19 ahead of full landing) ──

    @Test
    fun verify_returns_MalformedSeqMac_for_empty_seq_mac_hex() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "abc",
            sequenceTs = 0L,
            seqMacHex = "",
            verifyKeyHex = key.toLowerHex(),
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    @Test
    fun verify_returns_MalformedSeqMac_for_uppercase_seq_mac_hex() = runTest {
        // Server contract emits lowercase hex; uppercase is a strict
        // rejection so a hostile injection cannot use casing tricks to
        // bypass the validator.
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "abc",
            sequenceTs = 0L,
            seqMacHex = "A".repeat(64),
            verifyKeyHex = key.toLowerHex(),
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    @Test
    fun verify_returns_MalformedSeqMac_for_odd_length_seq_mac_hex() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "abc",
            sequenceTs = 0L,
            seqMacHex = "0".repeat(63),
            verifyKeyHex = key.toLowerHex(),
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    @Test
    fun verify_returns_MalformedSeqMac_for_short_then_padded_seq_mac_hex() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "abc",
            sequenceTs = 0L,
            seqMacHex = "0".repeat(32),
            verifyKeyHex = key.toLowerHex(),
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    @Test
    fun verify_returns_MalformedSeqMac_for_non_hex_char_seq_mac() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        val outcome = SeqMacVerifier.verify(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeId = "abc",
            sequenceTs = 0L,
            seqMacHex = "g".repeat(64),
            verifyKeyHex = key.toLowerHex(),
        )
        assertEquals(SeqMacVerifier.Outcome.MalformedSeqMac, outcome)
    }

    @Test
    fun verify_throws_when_identity_hex_length_is_wrong() = runTest {
        init()
        val key = deriveVerifyKey(zeroRoot(), ALL_A_IDENTITY)
        assertFails {
            SeqMacVerifier.verify(
                identityHex = "a".repeat(63), // off-by-one
                seq = 0L,
                envelopeId = "abc",
                sequenceTs = 0L,
                seqMacHex = "0".repeat(64),
                verifyKeyHex = key.toLowerHex(),
            )
        }
    }

    @Test
    fun verify_throws_when_verify_key_hex_length_is_wrong() = runTest {
        init()
        assertFails {
            SeqMacVerifier.verify(
                identityHex = ALL_A_IDENTITY,
                seq = 0L,
                envelopeId = "abc",
                sequenceTs = 0L,
                seqMacHex = "0".repeat(64),
                verifyKeyHex = "0".repeat(63), // off-by-one
            )
        }
    }

    // ── Encoding helper unit pins ────────────────────────────────────────────

    @Test
    fun writeU64BigEndian_encodes_zero_correctly() {
        val out = ByteArray(8)
        SeqMacVerifier.writeU64BigEndian(out, 0, 0L)
        assertTrue(out.all { it == 0.toByte() })
    }

    @Test
    fun writeU64BigEndian_encodes_one_in_lsb() {
        val out = ByteArray(8)
        SeqMacVerifier.writeU64BigEndian(out, 0, 1L)
        assertEquals(0.toByte(), out[0])
        assertEquals(0.toByte(), out[6])
        assertEquals(1.toByte(), out[7])
    }

    @Test
    fun writeU64BigEndian_encodes_negative_one_as_all_ones() {
        // -1L in two's complement is 0xFFFFFFFFFFFFFFFF — the byte
        // pattern is the SAME as the u64::MAX value on the Rust side.
        val out = ByteArray(8)
        SeqMacVerifier.writeU64BigEndian(out, 0, -1L)
        assertTrue(out.all { it == 0xFF.toByte() })
    }

    @Test
    fun writeU16BigEndian_encodes_in_high_low_order() {
        val out = ByteArray(2)
        SeqMacVerifier.writeU16BigEndian(out, 0, 0x1234)
        assertEquals(0x12.toByte(), out[0])
        assertEquals(0x34.toByte(), out[1])
    }

    @Test
    fun writeU16BigEndian_rejects_negative() {
        assertFails {
            SeqMacVerifier.writeU16BigEndian(ByteArray(2), 0, -1)
        }
    }

    @Test
    fun writeU16BigEndian_rejects_over_u16_max() {
        assertFails {
            SeqMacVerifier.writeU16BigEndian(ByteArray(2), 0, 0x10000)
        }
    }

    @Test
    fun canonical_input_length_matches_fixed_prefix_plus_envelope_id_bytes() = runTest {
        init()
        // No envelope_id bytes: 101 bytes.
        val empty = SeqMacVerifier.buildCanonicalInput(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeIdBytes = ByteArray(0),
            sequenceTs = 0L,
        )
        assertEquals(SeqMacVerifier.CANONICAL_INPUT_FIXED_BYTES, empty.size)
        // 5 envelope_id bytes: 106 bytes.
        val five = SeqMacVerifier.buildCanonicalInput(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeIdBytes = "hello".encodeToByteArray(),
            sequenceTs = 0L,
        )
        assertEquals(SeqMacVerifier.CANONICAL_INPUT_FIXED_BYTES + 5, five.size)
    }

    @Test
    fun canonical_input_starts_with_19_byte_domain_tag() = runTest {
        init()
        val out = SeqMacVerifier.buildCanonicalInput(
            identityHex = ALL_A_IDENTITY,
            seq = 0L,
            envelopeIdBytes = ByteArray(0),
            sequenceTs = 0L,
        )
        val expectedTag = "phantom-seq-mac-v1".encodeToByteArray() + byteArrayOf(0)
        assertEquals(19, expectedTag.size)
        val actualTag = out.copyOfRange(0, 19)
        assertContentByteEquals(expectedTag, actualTag, "domain tag bytes must match relay")
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private fun assertContentByteEquals(
        expected: ByteArray,
        actual: ByteArray,
        message: String = "",
    ) {
        assertEquals(
            expected.toLowerHex(),
            actual.toLowerHex(),
            if (message.isEmpty()) "byte arrays differ" else message,
        )
    }

    private fun assertContentByteNotEquals(
        a: ByteArray,
        b: ByteArray,
        message: String = "",
    ) {
        assertNotEquals(
            a.toLowerHex(),
            b.toLowerHex(),
            if (message.isEmpty()) "byte arrays must differ but were identical" else message,
        )
    }
}
