package phantom.android.screens.chat

data class EmojiItem(val emoji: String, val keywords: List<String>)
data class EmojiCategory(val id: String, val label: String, val items: List<EmojiItem>)

val EMOJI_CATEGORIES: List<EmojiCategory> = listOf(

    EmojiCategory("smileys", "Smileys", listOf(
        EmojiItem("😀", listOf("smile","grin","happy","joy")),
        EmojiItem("😁", listOf("beam","grin","happy")),
        EmojiItem("😂", listOf("laugh","cry","tears","lol","funny")),
        EmojiItem("🤣", listOf("rofl","laugh","funny","floor")),
        EmojiItem("😃", listOf("smile","open","happy")),
        EmojiItem("😄", listOf("smile","eye","happy")),
        EmojiItem("😅", listOf("sweat","nervous","phew")),
        EmojiItem("😆", listOf("laugh","satisfied","haha")),
        EmojiItem("😉", listOf("wink","flirt")),
        EmojiItem("😊", listOf("blush","smile","happy")),
        EmojiItem("😋", listOf("yum","delicious","tongue")),
        EmojiItem("😎", listOf("cool","sunglasses","awesome")),
        EmojiItem("😍", listOf("heart eyes","love","infatuated")),
        EmojiItem("🥰", listOf("hearts","love","smiling")),
        EmojiItem("😘", listOf("kiss","blow","love")),
        EmojiItem("😗", listOf("kiss","whistling")),
        EmojiItem("🤩", listOf("star struck","wow","excited","stars")),
        EmojiItem("🥳", listOf("party","celebrate","hat")),
        EmojiItem("😏", listOf("smirk","sly","flirt")),
        EmojiItem("😒", listOf("unamused","meh","unimpressed")),
        EmojiItem("😞", listOf("disappointed","sad","down")),
        EmojiItem("😔", listOf("pensive","sad","thoughtful")),
        EmojiItem("😟", listOf("worried","sad")),
        EmojiItem("😕", listOf("confused","hmm")),
        EmojiItem("🙁", listOf("sad","frown")),
        EmojiItem("☹️", listOf("sad","frown","unhappy")),
        EmojiItem("😣", listOf("persevere","struggling")),
        EmojiItem("😖", listOf("confounded")),
        EmojiItem("😫", listOf("tired","weary")),
        EmojiItem("😩", listOf("weary","tired")),
        EmojiItem("🥺", listOf("pleading","puppy eyes","begging")),
        EmojiItem("😢", listOf("cry","sad","tear")),
        EmojiItem("😭", listOf("sob","crying","loudly")),
        EmojiItem("😤", listOf("steam","triumph","angry")),
        EmojiItem("😠", listOf("angry","mad")),
        EmojiItem("😡", listOf("rage","red angry")),
        EmojiItem("🤬", listOf("swearing","angry","cursing")),
        EmojiItem("🤯", listOf("exploding head","mind blown","shocked")),
        EmojiItem("😳", listOf("flushed","embarrassed","surprised")),
        EmojiItem("🥵", listOf("hot","sweating","overheated")),
        EmojiItem("🥶", listOf("cold","frozen","freezing")),
        EmojiItem("😱", listOf("scream","shocked","fear","horror")),
        EmojiItem("😨", listOf("fearful","scared")),
        EmojiItem("😰", listOf("anxious","sweat","worried")),
        EmojiItem("😥", listOf("sad","relieved","disappointed")),
        EmojiItem("😓", listOf("downcast","sweat")),
        EmojiItem("🤗", listOf("hug","happy","warm")),
        EmojiItem("🤔", listOf("thinking","hmm","curious")),
        EmojiItem("🫠", listOf("melting","awkward")),
        EmojiItem("🤭", listOf("shush","oops","giggle")),
        EmojiItem("🤫", listOf("shush","quiet","secret")),
        EmojiItem("🤥", listOf("lying","pinocchio")),
        EmojiItem("😶", listOf("silence","no mouth","speechless")),
        EmojiItem("😐", listOf("neutral","blank","expressionless")),
        EmojiItem("😑", listOf("expressionless","straight face")),
        EmojiItem("😬", listOf("grimace","nervous","awkward")),
        EmojiItem("🙄", listOf("roll eyes","annoyed","whatever")),
        EmojiItem("😯", listOf("hushed","surprised")),
        EmojiItem("😦", listOf("frown","open mouth","shocked")),
        EmojiItem("😧", listOf("anguished","shocked")),
        EmojiItem("😮", listOf("surprised","open mouth")),
        EmojiItem("😲", listOf("astonished","shocked","wow")),
        EmojiItem("🥱", listOf("yawn","tired","bored")),
        EmojiItem("😴", listOf("sleep","zzz","tired")),
        EmojiItem("🤤", listOf("drool","hungry")),
        EmojiItem("😪", listOf("sleepy","tired")),
        EmojiItem("😵", listOf("dizzy","spinning","faint")),
        EmojiItem("🤐", listOf("zipper mouth","secret","quiet")),
        EmojiItem("🥴", listOf("woozy","drunk","dizzy")),
        EmojiItem("🤢", listOf("nauseated","sick","gross")),
        EmojiItem("🤮", listOf("vomit","sick","gross")),
        EmojiItem("🤧", listOf("sneeze","cold","sick")),
        EmojiItem("😷", listOf("mask","sick","doctor")),
        EmojiItem("🤒", listOf("thermometer","sick","fever")),
        EmojiItem("🤕", listOf("bandage","injured","hurt")),
        EmojiItem("🤑", listOf("money mouth","rich","cash")),
        EmojiItem("😈", listOf("devil","evil","smile")),
        EmojiItem("👿", listOf("angry devil","evil")),
        EmojiItem("💀", listOf("skull","death","dead","skeleton")),
        EmojiItem("☠️", listOf("skull crossbones","danger","dead")),
        EmojiItem("💩", listOf("poop","poo","funny")),
        EmojiItem("🤡", listOf("clown","joker")),
        EmojiItem("👹", listOf("ogre","monster","demon")),
        EmojiItem("👺", listOf("goblin","red","monster")),
        EmojiItem("👻", listOf("ghost","halloween","boo")),
        EmojiItem("👽", listOf("alien","ufo","extraterrestrial")),
        EmojiItem("👾", listOf("alien monster","game","pixel")),
        EmojiItem("🤖", listOf("robot","bot","android")),
    )),

    EmojiCategory("people", "People & Body", listOf(
        EmojiItem("👋", listOf("wave","hi","hello","bye")),
        EmojiItem("🤚", listOf("raised back hand")),
        EmojiItem("🖐️", listOf("hand","five","stop")),
        EmojiItem("✋", listOf("raised hand","high five","stop")),
        EmojiItem("🖖", listOf("vulcan","spock","live long")),
        EmojiItem("🫱", listOf("hand","right")),
        EmojiItem("🤜", listOf("fist bump","right","punch")),
        EmojiItem("🤛", listOf("fist bump","left")),
        EmojiItem("✊", listOf("fist","power","punch","solidarity")),
        EmojiItem("👊", listOf("oncoming fist","punch","hit")),
        EmojiItem("👏", listOf("clap","applause","bravo","praise")),
        EmojiItem("🙌", listOf("raised hands","praise","yay","celebration")),
        EmojiItem("🫶", listOf("heart hands","love","care")),
        EmojiItem("🤲", listOf("open hands","prayer")),
        EmojiItem("🤝", listOf("handshake","deal","agreement")),
        EmojiItem("🙏", listOf("pray","please","thank","namaste","hope")),
        EmojiItem("✌️", listOf("victory","peace","two")),
        EmojiItem("🤞", listOf("crossed fingers","luck","hope","wish")),
        EmojiItem("🫰", listOf("finger snap")),
        EmojiItem("🤟", listOf("love you gesture","rock","ily")),
        EmojiItem("🤘", listOf("sign of horns","rock","metal")),
        EmojiItem("👌", listOf("ok","perfect","fine")),
        EmojiItem("🤌", listOf("pinched","italian","chef's kiss")),
        EmojiItem("🤏", listOf("pinching","small","little")),
        EmojiItem("👈", listOf("point left","this way")),
        EmojiItem("👉", listOf("point right","this way")),
        EmojiItem("👆", listOf("point up","above")),
        EmojiItem("☝️", listOf("index pointing up","one","attention")),
        EmojiItem("🫵", listOf("point at viewer","you")),
        EmojiItem("👇", listOf("point down","below")),
        EmojiItem("👍", listOf("thumbs up","like","good","yes","approve")),
        EmojiItem("👎", listOf("thumbs down","dislike","no","bad")),
        EmojiItem("✍️", listOf("writing","pen","signature")),
        EmojiItem("💅", listOf("nail polish","nails","manicure","sassy")),
        EmojiItem("🫡", listOf("salute","respect","yessir")),
        EmojiItem("🤳", listOf("selfie","phone","photo")),
        EmojiItem("💪", listOf("flexed biceps","strong","muscle","gym")),
        EmojiItem("🦾", listOf("mechanical arm","prosthetic","strong")),
        EmojiItem("🦵", listOf("leg","kick")),
        EmojiItem("🦶", listOf("foot","kick")),
        EmojiItem("👂", listOf("ear","hear","listen")),
        EmojiItem("👃", listOf("nose","smell")),
        EmojiItem("🫀", listOf("anatomical heart","organ")),
        EmojiItem("🫁", listOf("lungs","breathe","organ")),
        EmojiItem("🧠", listOf("brain","smart","think","mind")),
        EmojiItem("🦷", listOf("tooth","dentist")),
        EmojiItem("👀", listOf("eyes","look","watch","see")),
        EmojiItem("👁️", listOf("eye","see","look","watch")),
        EmojiItem("👅", listOf("tongue","taste","lick")),
        EmojiItem("👄", listOf("lips","mouth","kiss")),
        EmojiItem("🫦", listOf("biting lip","anxious","flirt")),
        EmojiItem("🧒", listOf("child","kid","young")),
        EmojiItem("👦", listOf("boy")),
        EmojiItem("👧", listOf("girl")),
        EmojiItem("🧑", listOf("person","adult")),
        EmojiItem("👱", listOf("blond person")),
        EmojiItem("👨", listOf("man")),
        EmojiItem("🧔", listOf("beard","man")),
        EmojiItem("👩", listOf("woman")),
        EmojiItem("🧓", listOf("older person","senior")),
        EmojiItem("👴", listOf("old man","grandpa","senior")),
        EmojiItem("👵", listOf("old woman","grandma","senior")),
        EmojiItem("🙍", listOf("frown","person")),
        EmojiItem("🙎", listOf("pouting","person")),
        EmojiItem("🙅", listOf("no","gesturing no","stop")),
        EmojiItem("🙆", listOf("ok","gesturing ok")),
        EmojiItem("💁", listOf("information","toss hair","sassy")),
        EmojiItem("🙋", listOf("raise hand","question","yes","me")),
        EmojiItem("🧏", listOf("deaf person")),
        EmojiItem("🙇", listOf("bow","sorry","please")),
        EmojiItem("🤦", listOf("facepalm","disbelief","duh")),
        EmojiItem("🤷", listOf("shrug","whatever","idk","dunno")),
        EmojiItem("💆", listOf("massage","relax","spa")),
        EmojiItem("💇", listOf("haircut","salon")),
        EmojiItem("🚶", listOf("walking","person")),
        EmojiItem("🧍", listOf("standing","person")),
        EmojiItem("🧎", listOf("kneeling","person")),
        EmojiItem("🏃", listOf("running","jogging","exercise","run")),
        EmojiItem("💃", listOf("dance","woman","party")),
        EmojiItem("🕺", listOf("dance","man","party")),
        EmojiItem("🕴️", listOf("suit","levitate","businessman")),
        EmojiItem("👫", listOf("couple","man woman","together")),
        EmojiItem("👬", listOf("couple","two men","together")),
        EmojiItem("👭", listOf("couple","two women","together")),
        EmojiItem("👨‍👩‍👦", listOf("family","parents","child")),
        EmojiItem("👨‍👩‍👧", listOf("family","parents","daughter")),
    )),

    EmojiCategory("animals", "Animals & Nature", listOf(
        EmojiItem("🐶", listOf("dog","puppy","pet","woof")),
        EmojiItem("🐱", listOf("cat","kitten","meow","pet")),
        EmojiItem("🐭", listOf("mouse","rat")),
        EmojiItem("🐹", listOf("hamster","pet")),
        EmojiItem("🐰", listOf("rabbit","bunny","easter")),
        EmojiItem("🦊", listOf("fox","clever")),
        EmojiItem("🐻", listOf("bear","hug","teddy")),
        EmojiItem("🐼", listOf("panda","bamboo","china")),
        EmojiItem("🐨", listOf("koala","australia")),
        EmojiItem("🐯", listOf("tiger","fierce","roar")),
        EmojiItem("🦁", listOf("lion","king","roar","brave")),
        EmojiItem("🐮", listOf("cow","moo","farm")),
        EmojiItem("🐷", listOf("pig","oink","farm")),
        EmojiItem("🐸", listOf("frog","jump","green")),
        EmojiItem("🐵", listOf("monkey","ape","banana")),
        EmojiItem("🙈", listOf("see no evil","monkey","shy")),
        EmojiItem("🙉", listOf("hear no evil","monkey")),
        EmojiItem("🙊", listOf("speak no evil","monkey","oops")),
        EmojiItem("🐔", listOf("chicken","hen","farm")),
        EmojiItem("🐧", listOf("penguin","cold","arctic")),
        EmojiItem("🐦", listOf("bird","tweet")),
        EmojiItem("🦅", listOf("eagle","freedom","soar")),
        EmojiItem("🦆", listOf("duck","quack")),
        EmojiItem("🦉", listOf("owl","wise","night")),
        EmojiItem("🦇", listOf("bat","night","halloween","vampire")),
        EmojiItem("🐺", listOf("wolf","howl")),
        EmojiItem("🐗", listOf("boar","wild","pig")),
        EmojiItem("🐴", listOf("horse","pony","gallop")),
        EmojiItem("🦄", listOf("unicorn","magic","rainbow","fantasy")),
        EmojiItem("🐝", listOf("bee","honey","sting","busy")),
        EmojiItem("🐛", listOf("worm","caterpillar","bug")),
        EmojiItem("🦋", listOf("butterfly","beautiful","flutter")),
        EmojiItem("🐌", listOf("snail","slow")),
        EmojiItem("🐞", listOf("ladybug","luck","red")),
        EmojiItem("🐜", listOf("ant","colony","tiny")),
        EmojiItem("🦟", listOf("mosquito","bite","bug")),
        EmojiItem("🐢", listOf("turtle","slow","shell")),
        EmojiItem("🐍", listOf("snake","slither","danger")),
        EmojiItem("🦎", listOf("lizard","reptile")),
        EmojiItem("🦖", listOf("dinosaur","t-rex","extinct")),
        EmojiItem("🐙", listOf("octopus","tentacles","sea")),
        EmojiItem("🦑", listOf("squid","sea","ink")),
        EmojiItem("🦐", listOf("shrimp","seafood")),
        EmojiItem("🦞", listOf("lobster","seafood","red")),
        EmojiItem("🦀", listOf("crab","seafood","sideways")),
        EmojiItem("🐡", listOf("blowfish","fish","sea")),
        EmojiItem("🐠", listOf("tropical fish","colorful","sea")),
        EmojiItem("🐟", listOf("fish","sea","seafood")),
        EmojiItem("🐬", listOf("dolphin","smart","sea","jump")),
        EmojiItem("🐳", listOf("whale","sea","big","blow")),
        EmojiItem("🦈", listOf("shark","danger","sea","bite")),
        EmojiItem("🐊", listOf("crocodile","swamp","danger")),
        EmojiItem("🦒", listOf("giraffe","tall","africa")),
        EmojiItem("🐘", listOf("elephant","big","memory","africa")),
        EmojiItem("🦏", listOf("rhino","horn","africa")),
        EmojiItem("🦛", listOf("hippo","africa","water")),
        EmojiItem("🐪", listOf("camel","desert","hump")),
        EmojiItem("🦘", listOf("kangaroo","australia","jump","pouch")),
        EmojiItem("🦙", listOf("llama","fluffy","south america")),
        EmojiItem("🐿️", listOf("chipmunk","squirrel","acorn")),
        EmojiItem("🌸", listOf("cherry blossom","flower","pink","spring")),
        EmojiItem("💐", listOf("bouquet","flowers","gift")),
        EmojiItem("🌹", listOf("rose","love","red","flower")),
        EmojiItem("🥀", listOf("wilted flower","dead","sad")),
        EmojiItem("🌺", listOf("hibiscus","tropical","flower")),
        EmojiItem("🌻", listOf("sunflower","bright","summer")),
        EmojiItem("🌼", listOf("blossom","yellow","flower")),
        EmojiItem("🌷", listOf("tulip","flower","spring")),
        EmojiItem("🌱", listOf("seedling","grow","plant","sprout")),
        EmojiItem("🌿", listOf("herb","leaf","green","plant")),
        EmojiItem("☘️", listOf("shamrock","luck","ireland","clover")),
        EmojiItem("🍀", listOf("four leaf clover","luck","lucky")),
        EmojiItem("🍁", listOf("maple leaf","canada","autumn","fall")),
        EmojiItem("🍂", listOf("fallen leaf","autumn","fall")),
        EmojiItem("🍃", listOf("leaf","wind","blow","green")),
        EmojiItem("🪨", listOf("rock","stone","solid")),
        EmojiItem("🪵", listOf("wood","log","fire")),
        EmojiItem("🌊", listOf("wave","ocean","sea","surf")),
        EmojiItem("🌋", listOf("volcano","eruption","fire")),
        EmojiItem("⛰️", listOf("mountain","hike","climb")),
        EmojiItem("🏔️", listOf("snow mountain","peak","cold")),
        EmojiItem("🌈", listOf("rainbow","colorful","after rain")),
        EmojiItem("⚡", listOf("lightning","thunder","fast","electric","bolt")),
        EmojiItem("❄️", listOf("snowflake","cold","winter","ice")),
        EmojiItem("🔥", listOf("fire","hot","flame","lit","trending")),
        EmojiItem("💧", listOf("droplet","water","blue")),
        EmojiItem("🌙", listOf("crescent moon","night","sleep")),
        EmojiItem("⭐", listOf("star","good","rating","favorite")),
        EmojiItem("🌟", listOf("glowing star","sparkle","wow","amazing")),
        EmojiItem("✨", listOf("sparkles","shine","magic","pretty")),
        EmojiItem("🌞", listOf("sun face","sunny","warm","bright")),
        EmojiItem("☀️", listOf("sun","sunny","warm","bright","day")),
        EmojiItem("🌤️", listOf("sun behind cloud","partly cloudy")),
        EmojiItem("🌦️", listOf("rain","sun","weather")),
        EmojiItem("🌧️", listOf("rain","cloud","wet","storm")),
        EmojiItem("⛈️", listOf("thunderstorm","lightning","rain")),
        EmojiItem("🌨️", listOf("snow","cloud","winter","cold")),
        EmojiItem("🌪️", listOf("tornado","storm","wind","twister")),
    )),

    EmojiCategory("food", "Food & Drink", listOf(
        EmojiItem("🍎", listOf("apple","red","fruit","healthy")),
        EmojiItem("🍊", listOf("orange","tangerine","fruit","citrus")),
        EmojiItem("🍋", listOf("lemon","sour","citrus","yellow")),
        EmojiItem("🍇", listOf("grapes","wine","fruit","purple")),
        EmojiItem("🍓", listOf("strawberry","red","fruit","sweet")),
        EmojiItem("🫐", listOf("blueberry","fruit","blue")),
        EmojiItem("🍈", listOf("melon","fruit","green")),
        EmojiItem("🍉", listOf("watermelon","summer","fruit")),
        EmojiItem("🍑", listOf("peach","fruit","butt","soft")),
        EmojiItem("🍒", listOf("cherry","red","fruit","pair")),
        EmojiItem("🥭", listOf("mango","tropical","fruit")),
        EmojiItem("🍍", listOf("pineapple","tropical","fruit")),
        EmojiItem("🥝", listOf("kiwi","green","fruit")),
        EmojiItem("🍅", listOf("tomato","red","vegetable")),
        EmojiItem("🥑", listOf("avocado","green","healthy","toast")),
        EmojiItem("🍆", listOf("eggplant","purple","vegetable")),
        EmojiItem("🥕", listOf("carrot","orange","vegetable","healthy")),
        EmojiItem("🌽", listOf("corn","yellow","vegetable")),
        EmojiItem("🌶️", listOf("pepper","hot","spicy","red")),
        EmojiItem("🧄", listOf("garlic","flavor","cooking")),
        EmojiItem("🧅", listOf("onion","flavor","cooking","cry")),
        EmojiItem("🍄", listOf("mushroom","fungus","mario","forest")),
        EmojiItem("🥜", listOf("peanuts","nuts","snack")),
        EmojiItem("🍞", listOf("bread","toast","wheat","bake")),
        EmojiItem("🥐", listOf("croissant","french","breakfast","bakery")),
        EmojiItem("🥖", listOf("baguette","french","bread")),
        EmojiItem("🫓", listOf("flatbread","pita","bread")),
        EmojiItem("🧀", listOf("cheese","dairy","snack")),
        EmojiItem("🥚", listOf("egg","breakfast","cooking")),
        EmojiItem("🍳", listOf("cooking","frying","egg","breakfast")),
        EmojiItem("🥞", listOf("pancakes","breakfast","syrup","stack")),
        EmojiItem("🧇", listOf("waffle","breakfast","syrup")),
        EmojiItem("🥓", listOf("bacon","breakfast","meat","crispy")),
        EmojiItem("🥩", listOf("meat","steak","beef")),
        EmojiItem("🍗", listOf("chicken","poultry","food")),
        EmojiItem("🍖", listOf("meat on bone","bbq","food")),
        EmojiItem("🌭", listOf("hotdog","sausage","fast food")),
        EmojiItem("🍔", listOf("burger","fast food","beef","bun")),
        EmojiItem("🍟", listOf("fries","fast food","potato")),
        EmojiItem("🍕", listOf("pizza","italian","cheese","slice")),
        EmojiItem("🫔", listOf("tamale","wrap","food")),
        EmojiItem("🌮", listOf("taco","mexican","food")),
        EmojiItem("🌯", listOf("burrito","wrap","mexican","food")),
        EmojiItem("🥗", listOf("salad","green","healthy","bowl")),
        EmojiItem("🥘", listOf("paella","stew","pot","pan")),
        EmojiItem("🍜", listOf("noodles","ramen","soup","asian")),
        EmojiItem("🍝", listOf("spaghetti","pasta","italian")),
        EmojiItem("🍛", listOf("curry","rice","indian","spicy")),
        EmojiItem("🍣", listOf("sushi","japanese","fish","rice")),
        EmojiItem("🍱", listOf("bento","japanese","box","lunch")),
        EmojiItem("🍤", listOf("shrimp","tempura","fried","seafood")),
        EmojiItem("🍙", listOf("rice ball","japanese","onigiri")),
        EmojiItem("🍦", listOf("ice cream","soft serve","sweet","dessert")),
        EmojiItem("🍧", listOf("shaved ice","summer","sweet","dessert")),
        EmojiItem("🍨", listOf("ice cream","dessert","sweet")),
        EmojiItem("🍩", listOf("donut","sweet","dessert","ring")),
        EmojiItem("🍪", listOf("cookie","sweet","chocolate","dessert")),
        EmojiItem("🎂", listOf("birthday cake","celebrate","candles")),
        EmojiItem("🍰", listOf("cake","slice","dessert","sweet")),
        EmojiItem("🧁", listOf("cupcake","sweet","dessert","birthday")),
        EmojiItem("🍫", listOf("chocolate","candy","sweet","brown")),
        EmojiItem("🍬", listOf("candy","sweet","sugar","lollipop")),
        EmojiItem("🍭", listOf("lollipop","candy","sweet","colorful")),
        EmojiItem("☕", listOf("coffee","hot","cafe","morning","espresso")),
        EmojiItem("🫖", listOf("teapot","tea","hot","drink")),
        EmojiItem("🧋", listOf("bubble tea","milk tea","boba")),
        EmojiItem("🍵", listOf("tea","hot","green tea","matcha")),
        EmojiItem("🥤", listOf("cup","straw","drink","soda")),
        EmojiItem("🧃", listOf("juice","box","drink","fruit")),
        EmojiItem("🍺", listOf("beer","cheers","drink","mug")),
        EmojiItem("🍻", listOf("beers","cheers","toast","drink")),
        EmojiItem("🥂", listOf("champagne","celebrate","toast","party")),
        EmojiItem("🍷", listOf("wine","glass","red","drink")),
        EmojiItem("🥃", listOf("whiskey","bourbon","tumbler","drink")),
        EmojiItem("🍸", listOf("cocktail","martini","drink","party")),
        EmojiItem("🍹", listOf("tropical drink","cocktail","umbrella","summer")),
        EmojiItem("🧉", listOf("mate","tea","drink","argentina")),
        EmojiItem("🍾", listOf("champagne","bottle","celebrate","pop")),
        EmojiItem("🫗", listOf("pouring","liquid","drink")),
    )),

    EmojiCategory("activities", "Activities", listOf(
        EmojiItem("⚽", listOf("soccer","football","sport","ball","kick")),
        EmojiItem("🏀", listOf("basketball","sport","ball","hoop")),
        EmojiItem("🏈", listOf("american football","sport","ball","nfl")),
        EmojiItem("⚾", listOf("baseball","sport","ball")),
        EmojiItem("🥎", listOf("softball","sport","ball")),
        EmojiItem("🎾", listOf("tennis","sport","ball","racket")),
        EmojiItem("🏐", listOf("volleyball","sport","ball")),
        EmojiItem("🏉", listOf("rugby","sport","ball")),
        EmojiItem("🥏", listOf("flying disc","frisbee","sport")),
        EmojiItem("🎱", listOf("pool","billiards","8ball","game")),
        EmojiItem("🏓", listOf("table tennis","ping pong","sport")),
        EmojiItem("🏸", listOf("badminton","sport","racket","shuttle")),
        EmojiItem("🥊", listOf("boxing","glove","fight","punch","sport")),
        EmojiItem("🥋", listOf("martial arts","karate","sport","uniform")),
        EmojiItem("🎽", listOf("running shirt","sport","exercise")),
        EmojiItem("🛹", listOf("skateboard","skate","sport","cool")),
        EmojiItem("🛼", listOf("roller skate","sport","wheels")),
        EmojiItem("🛷", listOf("sled","snow","winter","slide")),
        EmojiItem("⛸️", listOf("ice skate","winter","sport")),
        EmojiItem("🏋️", listOf("weightlifting","gym","strong","workout")),
        EmojiItem("🤼", listOf("wrestling","sport","fight")),
        EmojiItem("🤸", listOf("gymnastics","cartwheel","flexible")),
        EmojiItem("⛹️", listOf("basketball","bouncing","sport")),
        EmojiItem("🤺", listOf("fencing","sword","sport")),
        EmojiItem("🏊", listOf("swimming","pool","sport","water")),
        EmojiItem("🚴", listOf("cycling","bike","sport","ride")),
        EmojiItem("🏄", listOf("surfing","waves","sport","beach")),
        EmojiItem("🧘", listOf("yoga","meditation","lotus","calm","relax")),
        EmojiItem("🧗", listOf("climbing","rock","sport","mountain")),
        EmojiItem("🤾", listOf("handball","sport","throw")),
        EmojiItem("🏇", listOf("horse racing","sport","jockey")),
        EmojiItem("⛷️", listOf("skiing","snow","winter","sport")),
        EmojiItem("🏂", listOf("snowboarding","snow","winter","sport")),
        EmojiItem("🪂", listOf("parachute","skydiving","jump","fly")),
        EmojiItem("🏋️", listOf("lifting","gym","weights","strong")),
        EmojiItem("🎯", listOf("target","bullseye","dart","aim","hit","goal")),
        EmojiItem("🎮", listOf("game","controller","video game","play","gaming")),
        EmojiItem("🕹️", listOf("joystick","game","arcade","retro")),
        EmojiItem("🎲", listOf("dice","game","luck","random","roll")),
        EmojiItem("♟️", listOf("chess","strategy","game","piece")),
        EmojiItem("🧩", listOf("puzzle","jigsaw","solve","piece")),
        EmojiItem("🎭", listOf("performing arts","theater","drama","masks")),
        EmojiItem("🎨", listOf("art","palette","painting","creative","design")),
        EmojiItem("🖼️", listOf("frame","picture","art","painting")),
        EmojiItem("🎬", listOf("clapper","film","movie","action","director")),
        EmojiItem("🎤", listOf("microphone","sing","music","performance")),
        EmojiItem("🎧", listOf("headphone","music","listen","audio")),
        EmojiItem("🎼", listOf("musical score","notes","music","sheet")),
        EmojiItem("🎹", listOf("piano","keyboard","music","instrument")),
        EmojiItem("🎸", listOf("guitar","rock","music","instrument")),
        EmojiItem("🎺", listOf("trumpet","jazz","music","instrument")),
        EmojiItem("🎻", listOf("violin","classical","music","instrument")),
        EmojiItem("🥁", listOf("drum","beat","music","rhythm")),
        EmojiItem("🎵", listOf("note","music","song","melody")),
        EmojiItem("🎶", listOf("notes","music","melody","song","singing")),
        EmojiItem("🎤", listOf("microphone","karaoke","sing","voice")),
        EmojiItem("🎙️", listOf("studio microphone","podcast","record")),
        EmojiItem("🎚️", listOf("level slider","audio","dj","mix")),
        EmojiItem("🎷", listOf("saxophone","jazz","music","instrument")),
        EmojiItem("🪗", listOf("accordion","music","instrument")),
        EmojiItem("🪘", listOf("long drum","music","rhythm")),
    )),

    EmojiCategory("travel", "Travel & Places", listOf(
        EmojiItem("🚗", listOf("car","drive","vehicle","red","road")),
        EmojiItem("🚙", listOf("suv","car","drive","vehicle")),
        EmojiItem("🚕", listOf("taxi","cab","yellow","car")),
        EmojiItem("🚌", listOf("bus","transport","public","school")),
        EmojiItem("🚎", listOf("trolleybus","transport","electric")),
        EmojiItem("🏎️", listOf("racing car","fast","speed","formula")),
        EmojiItem("🚓", listOf("police car","cop","law")),
        EmojiItem("🚑", listOf("ambulance","emergency","hospital","medical")),
        EmojiItem("🚒", listOf("fire truck","emergency","red","fire")),
        EmojiItem("🚐", listOf("minibus","van","transport")),
        EmojiItem("🛻", listOf("pickup truck","vehicle","truck")),
        EmojiItem("🚚", listOf("delivery truck","cargo","shipping")),
        EmojiItem("🚛", listOf("semi truck","freight","big")),
        EmojiItem("🚜", listOf("tractor","farm","agriculture")),
        EmojiItem("🛵", listOf("scooter","moped","motor")),
        EmojiItem("🏍️", listOf("motorcycle","bike","ride","fast")),
        EmojiItem("🚲", listOf("bicycle","bike","cycle","eco")),
        EmojiItem("🛴", listOf("kick scooter","micro","city")),
        EmojiItem("🛺", listOf("auto rickshaw","tuk tuk","asia")),
        EmojiItem("🚁", listOf("helicopter","fly","rotor","transport")),
        EmojiItem("✈️", listOf("airplane","fly","flight","travel","plane")),
        EmojiItem("🛩️", listOf("small airplane","private","fly")),
        EmojiItem("🚀", listOf("rocket","space","launch","fast","nasa")),
        EmojiItem("🛸", listOf("ufo","alien","flying saucer","space")),
        EmojiItem("⛵", listOf("sailboat","sea","boat","sail")),
        EmojiItem("🛥️", listOf("speedboat","motor","fast","water")),
        EmojiItem("🚢", listOf("ship","cruise","sea","ocean","boat")),
        EmojiItem("⚓", listOf("anchor","port","heavy","sea")),
        EmojiItem("🚂", listOf("train","locomotive","steam","rail")),
        EmojiItem("🚃", listOf("train","railway car","metro")),
        EmojiItem("🚄", listOf("bullet train","fast","shinkansen","japan")),
        EmojiItem("🚅", listOf("high speed train","fast","rail")),
        EmojiItem("🚇", listOf("metro","subway","underground","train")),
        EmojiItem("🚊", listOf("tram","streetcar","city")),
        EmojiItem("🚞", listOf("mountain railway","cable","train")),
        EmojiItem("🛤️", listOf("railway track","rail","train")),
        EmojiItem("🏠", listOf("house","home","building","family")),
        EmojiItem("🏡", listOf("house","garden","home","yard")),
        EmojiItem("🏢", listOf("office","building","work","city")),
        EmojiItem("🏣", listOf("post office","japan","mail")),
        EmojiItem("🏥", listOf("hospital","medical","health","doctor")),
        EmojiItem("🏦", listOf("bank","money","finance","building")),
        EmojiItem("🏨", listOf("hotel","stay","room","travel")),
        EmojiItem("🏪", listOf("store","shop","convenience","retail")),
        EmojiItem("🏫", listOf("school","education","building","learn")),
        EmojiItem("🏬", listOf("department store","shop","mall")),
        EmojiItem("🏰", listOf("castle","europe","medieval","fairy tale")),
        EmojiItem("🏯", listOf("japanese castle","japan","samurai")),
        EmojiItem("🗼", listOf("tokyo tower","japan","landmark")),
        EmojiItem("🗽", listOf("statue of liberty","nyc","new york","usa")),
        EmojiItem("⛪", listOf("church","religion","cross","pray")),
        EmojiItem("🕌", listOf("mosque","islam","religion","prayer")),
        EmojiItem("⛩️", listOf("shinto shrine","japan","torii","gate")),
        EmojiItem("🕍", listOf("synagogue","jewish","religion")),
        EmojiItem("🗺️", listOf("map","world","navigate","travel","geography")),
        EmojiItem("🧭", listOf("compass","navigate","direction","north")),
        EmojiItem("🏖️", listOf("beach","sand","summer","vacation","sun")),
        EmojiItem("🏝️", listOf("island","tropical","desert","stranded")),
        EmojiItem("🏕️", listOf("camping","tent","outdoors","nature")),
        EmojiItem("🌉", listOf("bridge","night","city","light")),
        EmojiItem("🌆", listOf("city","dusk","buildings","sunset")),
        EmojiItem("🌇", listOf("city","sunset","buildings","golden hour")),
        EmojiItem("🌃", listOf("night","city","stars","dark")),
        EmojiItem("🌁", listOf("fog","city","foggy")),
        EmojiItem("🗻", listOf("mount fuji","japan","mountain","snow")),
        EmojiItem("🏔️", listOf("mountain","snow","peak","hike")),
        EmojiItem("🌍", listOf("earth","world","africa","europe","globe")),
        EmojiItem("🌎", listOf("earth","world","america","globe")),
        EmojiItem("🌏", listOf("earth","world","asia","pacific","globe")),
    )),

    EmojiCategory("objects", "Objects", listOf(
        EmojiItem("⌚", listOf("watch","time","clock","wrist")),
        EmojiItem("📱", listOf("phone","mobile","cell","smartphone","iphone","android")),
        EmojiItem("💻", listOf("laptop","computer","mac","work","screen")),
        EmojiItem("⌨️", listOf("keyboard","type","computer","keys")),
        EmojiItem("🖥️", listOf("desktop","computer","monitor","screen")),
        EmojiItem("🖨️", listOf("printer","print","paper")),
        EmojiItem("🖱️", listOf("mouse","computer","click","cursor")),
        EmojiItem("🗜️", listOf("clamp","vise","compress")),
        EmojiItem("💾", listOf("floppy disk","save","storage","retro")),
        EmojiItem("💿", listOf("cd","disc","music","data")),
        EmojiItem("📀", listOf("dvd","disc","data","movie")),
        EmojiItem("📷", listOf("camera","photo","picture","snap")),
        EmojiItem("📸", listOf("camera","flash","photo","selfie")),
        EmojiItem("📹", listOf("camera","video","record","film")),
        EmojiItem("🎥", listOf("movie camera","film","director","cinema")),
        EmojiItem("📟", listOf("pager","retro","beeper")),
        EmojiItem("📠", listOf("fax","machine","office")),
        EmojiItem("📺", listOf("tv","television","screen","watch")),
        EmojiItem("📻", listOf("radio","music","broadcast","listen")),
        EmojiItem("🧭", listOf("compass","navigate","direction")),
        EmojiItem("⏱️", listOf("stopwatch","time","fast","timer")),
        EmojiItem("⏲️", listOf("timer","clock","alarm")),
        EmojiItem("⏰", listOf("alarm","clock","wake","morning")),
        EmojiItem("🕰️", listOf("mantelpiece clock","antique","time")),
        EmojiItem("📡", listOf("satellite","antenna","signal","space")),
        EmojiItem("🔋", listOf("battery","charge","power","energy")),
        EmojiItem("🪫", listOf("low battery","drain","empty")),
        EmojiItem("🔌", listOf("plug","power","electric","charge")),
        EmojiItem("💡", listOf("lightbulb","idea","bright","electric","innovation")),
        EmojiItem("🔦", listOf("flashlight","torch","light","dark")),
        EmojiItem("🕯️", listOf("candle","light","romance","dinner","flame")),
        EmojiItem("🗑️", listOf("wastebasket","trash","bin","delete")),
        EmojiItem("💰", listOf("money","bag","rich","cash","dollar")),
        EmojiItem("💳", listOf("credit card","pay","bank","wallet")),
        EmojiItem("💎", listOf("gem","diamond","jewel","luxury","bling")),
        EmojiItem("⚖️", listOf("scale","justice","law","balance")),
        EmojiItem("🔧", listOf("wrench","tool","repair","fix")),
        EmojiItem("🔨", listOf("hammer","tool","build","construct","nail")),
        EmojiItem("⛏️", listOf("pickaxe","mine","dig","tool")),
        EmojiItem("🔩", listOf("bolt","nut","tool","screw")),
        EmojiItem("🪛", listOf("screwdriver","tool","fix")),
        EmojiItem("🪚", listOf("saw","wood","tool","cut")),
        EmojiItem("🔫", listOf("gun","pistol","squirt","toy")),
        EmojiItem("🧲", listOf("magnet","attract","pull","metal")),
        EmojiItem("🪝", listOf("hook","hang","catch")),
        EmojiItem("🧰", listOf("toolbox","fix","repair","tools")),
        EmojiItem("🧱", listOf("brick","wall","build","lego")),
        EmojiItem("🪜", listOf("ladder","climb","step")),
        EmojiItem("🚪", listOf("door","open","close","room")),
        EmojiItem("🪞", listOf("mirror","reflection","beauty")),
        EmojiItem("🪟", listOf("window","view","light","glass")),
        EmojiItem("🛏️", listOf("bed","sleep","rest","room")),
        EmojiItem("🛋️", listOf("couch","sofa","relax","lounge")),
        EmojiItem("🚿", listOf("shower","clean","wash","bath")),
        EmojiItem("🛁", listOf("bathtub","soak","relax","bath")),
        EmojiItem("🪠", listOf("plunger","toilet","unclog")),
        EmojiItem("🧴", listOf("lotion","cream","skincare","bottle")),
        EmojiItem("🧷", listOf("safety pin","sew","needle","attach")),
        EmojiItem("🧹", listOf("broom","sweep","clean","witch")),
        EmojiItem("🧺", listOf("basket","laundry","wicker")),
        EmojiItem("🧻", listOf("toilet paper","roll","tissue","bathroom")),
        EmojiItem("🪣", listOf("bucket","water","clean","fill")),
        EmojiItem("🧼", listOf("soap","wash","clean","bubble","hygiene")),
        EmojiItem("🫧", listOf("bubbles","soap","foam","clean")),
        EmojiItem("🪥", listOf("toothbrush","teeth","clean","dental")),
        EmojiItem("🧽", listOf("sponge","clean","scrub","wash")),
        EmojiItem("🧯", listOf("extinguisher","fire","safety","emergency")),
        EmojiItem("🛒", listOf("shopping cart","grocery","buy","retail")),
        EmojiItem("🚬", listOf("cigarette","smoke","tobacco")),
        EmojiItem("⚰️", listOf("coffin","funeral","death","rip")),
        EmojiItem("⚱️", listOf("urn","ashes","funeral")),
        EmojiItem("🗿", listOf("moai","easter island","stone","ancient")),
        EmojiItem("🪆", listOf("nesting doll","russian","matryoshka")),
        EmojiItem("🪅", listOf("pinata","party","mexico","break")),
        EmojiItem("🎁", listOf("gift","present","wrap","birthday","surprise")),
        EmojiItem("🎀", listOf("ribbon","bow","gift","pink")),
        EmojiItem("🎊", listOf("confetti","party","celebrate","ball")),
        EmojiItem("🎉", listOf("party","celebrate","tada","congrats","birthday")),
        EmojiItem("🎈", listOf("balloon","party","red","celebrate")),
        EmojiItem("🎋", listOf("tanabata tree","bamboo","japan","wish")),
        EmojiItem("🎍", listOf("pine decoration","japan","new year")),
        EmojiItem("🎎", listOf("japanese dolls","festival","hinamatsuri")),
        EmojiItem("🎏", listOf("carp streamer","japan","kite","fish")),
        EmojiItem("🎐", listOf("wind chime","japan","summer","sound")),
        EmojiItem("🧧", listOf("red envelope","chinese","money","luck","new year")),
        EmojiItem("🎑", listOf("moon viewing","japan","autumn")),
        EmojiItem("📦", listOf("package","box","delivery","ship","parcel")),
        EmojiItem("📮", listOf("mailbox","post","letter")),
        EmojiItem("📪", listOf("mailbox","closed","empty","post")),
        EmojiItem("📫", listOf("mailbox","closed","mail","post")),
        EmojiItem("📬", listOf("mailbox","open","flag","mail")),
        EmojiItem("📭", listOf("mailbox","open","empty")),
        EmojiItem("📮", listOf("postbox","mail","post","red")),
        EmojiItem("📯", listOf("postal horn","bugle","instrument")),
        EmojiItem("📜", listOf("scroll","ancient","document","parchment")),
        EmojiItem("📃", listOf("page","document","curl","text")),
        EmojiItem("📄", listOf("page","document","white","text")),
        EmojiItem("📑", listOf("bookmark tabs","document","divider")),
        EmojiItem("🗒️", listOf("spiral notepad","notes","write")),
        EmojiItem("🗓️", listOf("spiral calendar","schedule","date","plan")),
        EmojiItem("📆", listOf("tear-off calendar","date","schedule")),
        EmojiItem("📅", listOf("calendar","date","schedule","plan")),
        EmojiItem("🗑️", listOf("trash","delete","bin","remove")),
        EmojiItem("📁", listOf("folder","files","directory","organize")),
        EmojiItem("📂", listOf("folder","open","files","organize")),
        EmojiItem("🗂️", listOf("card index","dividers","organize")),
        EmojiItem("🗃️", listOf("card file box","archive","organize")),
        EmojiItem("🗄️", listOf("file cabinet","archive","office","drawers")),
        EmojiItem("📊", listOf("bar chart","stats","data","graph","analytics")),
        EmojiItem("📈", listOf("chart up","growth","increase","stock","trend")),
        EmojiItem("📉", listOf("chart down","decrease","loss","stock","trend")),
        EmojiItem("🗒️", listOf("notepad","notes","write","spiral")),
        EmojiItem("📋", listOf("clipboard","list","checklist","task")),
        EmojiItem("📌", listOf("pushpin","pin","map","location","mark")),
        EmojiItem("📍", listOf("round pushpin","pin","location","map","mark")),
        EmojiItem("📎", listOf("paperclip","attach","clip","office")),
        EmojiItem("🖇️", listOf("paperclips","linked","attach","office")),
        EmojiItem("📏", listOf("ruler","measure","straight","line")),
        EmojiItem("📐", listOf("triangular ruler","measure","angle","geometry")),
        EmojiItem("✂️", listOf("scissors","cut","trim","craft")),
        EmojiItem("🗃️", listOf("card box","file","archive","organize")),
        EmojiItem("🖊️", listOf("pen","write","edit","blue")),
        EmojiItem("✏️", listOf("pencil","write","draw","edit","sketch")),
        EmojiItem("🖋️", listOf("fountain pen","write","signature","ink")),
        EmojiItem("🖌️", listOf("paintbrush","art","paint","creative")),
        EmojiItem("🖍️", listOf("crayon","color","draw","kids")),
        EmojiItem("📝", listOf("memo","write","note","pencil","edit")),
        EmojiItem("🔍", listOf("magnifying glass","search","find","zoom","look")),
        EmojiItem("🔎", listOf("magnifying glass right","search","find","zoom")),
        EmojiItem("🔐", listOf("locked key","secure","private","crypto","password")),
        EmojiItem("🔏", listOf("locked pen","secure","private","sign")),
        EmojiItem("🔒", listOf("locked","secure","private","encrypted","safe")),
        EmojiItem("🔓", listOf("unlocked","open","insecure","free")),
        EmojiItem("🔑", listOf("key","open","access","password","unlock")),
        EmojiItem("🗝️", listOf("old key","antique","unlock","vintage")),
    )),

    EmojiCategory("symbols", "Symbols", listOf(
        EmojiItem("❤️", listOf("heart","love","red","romance","care")),
        EmojiItem("🧡", listOf("orange heart","love","warm")),
        EmojiItem("💛", listOf("yellow heart","love","happy","friendship")),
        EmojiItem("💚", listOf("green heart","nature","love","health")),
        EmojiItem("💙", listOf("blue heart","love","trust","calm")),
        EmojiItem("💜", listOf("purple heart","love","compassion","military")),
        EmojiItem("🖤", listOf("black heart","dark","love","evil","goth")),
        EmojiItem("🤍", listOf("white heart","love","pure","clean")),
        EmojiItem("🤎", listOf("brown heart","love","earth","warmth")),
        EmojiItem("💔", listOf("broken heart","sad","heartbreak","pain")),
        EmojiItem("❣️", listOf("heart exclamation","love","care")),
        EmojiItem("💕", listOf("two hearts","love","cute","romance")),
        EmojiItem("💞", listOf("revolving hearts","love","romance","spin")),
        EmojiItem("💓", listOf("beating heart","love","pulse")),
        EmojiItem("💗", listOf("growing heart","love","bigger")),
        EmojiItem("💖", listOf("sparkling heart","love","twinkle")),
        EmojiItem("💝", listOf("heart ribbon","love","gift")),
        EmojiItem("💘", listOf("heart arrow","love","cupid","valentine")),
        EmojiItem("💟", listOf("heart decoration","ornament","love")),
        EmojiItem("☮️", listOf("peace","symbol","anti-war","hippie")),
        EmojiItem("✝️", listOf("cross","christian","religion","church")),
        EmojiItem("☪️", listOf("star crescent","islam","religion","moon")),
        EmojiItem("🕉️", listOf("om","hindu","buddhist","meditation")),
        EmojiItem("✡️", listOf("star of david","jewish","judaism")),
        EmojiItem("🔯", listOf("dotted six-pointed star","jewish","hex")),
        EmojiItem("🕎", listOf("menorah","jewish","hanukkah","candles")),
        EmojiItem("☯️", listOf("yin yang","balance","tao","harmony")),
        EmojiItem("♻️", listOf("recycle","eco","green","reuse")),
        EmojiItem("⚜️", listOf("fleur-de-lis","heraldry","france")),
        EmojiItem("🔱", listOf("trident","poseidon","sea","symbol")),
        EmojiItem("📛", listOf("name badge","label","identity")),
        EmojiItem("🔰", listOf("beginner","japan","symbol","new")),
        EmojiItem("⭕", listOf("circle","red","ring","o","correct")),
        EmojiItem("✅", listOf("check","done","yes","correct","approved","ok","complete")),
        EmojiItem("☑️", listOf("check box","done","tick","complete")),
        EmojiItem("✔️", listOf("check","tick","yes","correct","done")),
        EmojiItem("❌", listOf("cross","no","wrong","error","x","delete","cancel")),
        EmojiItem("❎", listOf("cross button","no","x","cancel")),
        EmojiItem("➕", listOf("plus","add","new","more","math")),
        EmojiItem("➖", listOf("minus","subtract","less","math")),
        EmojiItem("➗", listOf("divide","math","split")),
        EmojiItem("✖️", listOf("multiply","times","x","math")),
        EmojiItem("🟰", listOf("equals","same","math")),
        EmojiItem("♾️", listOf("infinity","forever","loop","unlimited")),
        EmojiItem("💯", listOf("100","perfect","score","full","hundred","yes","fire")),
        EmojiItem("🔴", listOf("red circle","dot","stop","danger")),
        EmojiItem("🟠", listOf("orange circle","dot","warning")),
        EmojiItem("🟡", listOf("yellow circle","dot","caution")),
        EmojiItem("🟢", listOf("green circle","dot","go","online","active")),
        EmojiItem("🔵", listOf("blue circle","dot","info")),
        EmojiItem("🟣", listOf("purple circle","dot")),
        EmojiItem("⚫", listOf("black circle","dot","dark")),
        EmojiItem("⚪", listOf("white circle","dot","light")),
        EmojiItem("🟤", listOf("brown circle","dot")),
        EmojiItem("🔺", listOf("red triangle up","arrow","warning")),
        EmojiItem("🔻", listOf("red triangle down","arrow","decrease")),
        EmojiItem("💠", listOf("diamond with dot","blue","ornament")),
        EmojiItem("🔷", listOf("large blue diamond","shape")),
        EmojiItem("🔶", listOf("large orange diamond","shape","warning")),
        EmojiItem("🔸", listOf("small orange diamond","shape")),
        EmojiItem("🔹", listOf("small blue diamond","shape")),
        EmojiItem("🔘", listOf("radio button","selected")),
        EmojiItem("🔲", listOf("black square button","button")),
        EmojiItem("🔳", listOf("white square button","button")),
        EmojiItem("▪️", listOf("small black square","dot","bullet")),
        EmojiItem("▫️", listOf("small white square","empty","dot")),
        EmojiItem("◾", listOf("medium black square","bullet")),
        EmojiItem("◽", listOf("medium white square","empty")),
        EmojiItem("◼️", listOf("medium-large black square")),
        EmojiItem("◻️", listOf("medium-large white square")),
        EmojiItem("⬛", listOf("large black square","dark")),
        EmojiItem("⬜", listOf("large white square","light","empty")),
        EmojiItem("🟥", listOf("red square","color","red")),
        EmojiItem("🟧", listOf("orange square","color","orange")),
        EmojiItem("🟨", listOf("yellow square","color","yellow")),
        EmojiItem("🟩", listOf("green square","color","green")),
        EmojiItem("🟦", listOf("blue square","color","blue")),
        EmojiItem("🟪", listOf("purple square","color","purple")),
        EmojiItem("⬛", listOf("black square","dark")),
        EmojiItem("🔊", listOf("speaker","loud","volume","sound","audio")),
        EmojiItem("🔇", listOf("muted","silent","no sound","quiet")),
        EmojiItem("🔔", listOf("bell","notification","ring","alert")),
        EmojiItem("🔕", listOf("bell slash","silent","no notifications","quiet")),
        EmojiItem("🔈", listOf("speaker","low volume","quiet","sound")),
        EmojiItem("🔉", listOf("speaker","medium volume","sound")),
        EmojiItem("📣", listOf("megaphone","announce","loud","cheer")),
        EmojiItem("📢", listOf("loudspeaker","announce","broadcast","public")),
        EmojiItem("🗣️", listOf("speaking head","talk","speak","voice")),
        EmojiItem("💬", listOf("speech","bubble","chat","comment","talk")),
        EmojiItem("💭", listOf("thought bubble","think","imagine","dream")),
        EmojiItem("🗯️", listOf("anger bubble","mad","shout","furious")),
        EmojiItem("♠️", listOf("spade","card","suit","game")),
        EmojiItem("♥️", listOf("heart","card","suit","game","red")),
        EmojiItem("♦️", listOf("diamond","card","suit","game","red")),
        EmojiItem("♣️", listOf("club","card","suit","game")),
        EmojiItem("🃏", listOf("joker","wild","card","game")),
        EmojiItem("🀄", listOf("mahjong","game","red","chinese")),
        EmojiItem("🎴", listOf("flower playing cards","hanafuda","japanese","game")),
        EmojiItem("⚠️", listOf("warning","caution","alert","danger","attention")),
        EmojiItem("🚫", listOf("no","prohibited","ban","stop","not allowed")),
        EmojiItem("⛔", listOf("no entry","stop","forbidden","circle")),
        EmojiItem("🚷", listOf("no pedestrians","forbidden")),
        EmojiItem("📵", listOf("no mobile phones","silent","forbidden")),
        EmojiItem("🔞", listOf("no under eighteen","adult","age","restricted")),
        EmojiItem("📴", listOf("mobile off","phone","silent")),
        EmojiItem("🆕", listOf("new","badge","label","fresh")),
        EmojiItem("🆙", listOf("up","update","button")),
        EmojiItem("🆒", listOf("cool","badge","awesome")),
        EmojiItem("🆓", listOf("free","no cost","gratis")),
        EmojiItem("🆖", listOf("ng","not good","no go")),
        EmojiItem("🆗", listOf("ok","approved","confirmed","yes")),
        EmojiItem("🆘", listOf("sos","help","emergency","danger","rescue")),
        EmojiItem("🆔", listOf("id","identity","card")),
        EmojiItem("🔤", listOf("abc","letters","alphabet","text")),
        EmojiItem("🔡", listOf("abc","lowercase","alphabet")),
        EmojiItem("🔢", listOf("numbers","digits","input")),
        EmojiItem("🔣", listOf("symbols","input","characters")),
        EmojiItem("🔠", listOf("abc","uppercase","alphabet")),
        EmojiItem("🔀", listOf("shuffle","random","mix","arrows")),
        EmojiItem("🔁", listOf("repeat","loop","cycle","arrows")),
        EmojiItem("🔂", listOf("repeat one","loop","single")),
        EmojiItem("▶️", listOf("play","start","video","media","arrow")),
        EmojiItem("⏸️", listOf("pause","stop","media","hold")),
        EmojiItem("⏹️", listOf("stop","square","media","end")),
        EmojiItem("⏺️", listOf("record","red dot","capture")),
        EmojiItem("⏭️", listOf("next track","skip","forward","fast")),
        EmojiItem("⏮️", listOf("previous track","back","rewind")),
        EmojiItem("⏩", listOf("fast forward","speed","double arrow")),
        EmojiItem("⏪", listOf("rewind","back","fast","double arrow")),
        EmojiItem("⏫", listOf("fast up","double arrow","up")),
        EmojiItem("⏬", listOf("fast down","double arrow","down")),
        EmojiItem("🔃", listOf("clockwise arrows","reload","sync","refresh")),
        EmojiItem("🔄", listOf("counterclockwise","refresh","cycle","sync")),
    )),

    EmojiCategory("flags", "Flags", listOf(
        EmojiItem("🏳️", listOf("white flag","surrender","peace")),
        EmojiItem("🏴", listOf("black flag","pirate","skull")),
        EmojiItem("🏁", listOf("checkered flag","race","finish","win")),
        EmojiItem("🚩", listOf("red flag","warning","alert","mark")),
        EmojiItem("🏳️‍🌈", listOf("rainbow flag","pride","lgbtq","gay")),
        EmojiItem("🏳️‍⚧️", listOf("transgender flag","trans","pride")),
        EmojiItem("🏴‍☠️", listOf("pirate flag","jolly roger","skull","danger")),
        EmojiItem("🇺🇸", listOf("usa","united states","america","flag")),
        EmojiItem("🇬🇧", listOf("uk","united kingdom","england","british","flag")),
        EmojiItem("🇷🇺", listOf("russia","russian","flag")),
        EmojiItem("🇩🇪", listOf("germany","german","deutschland","flag")),
        EmojiItem("🇫🇷", listOf("france","french","flag")),
        EmojiItem("🇯🇵", listOf("japan","japanese","nippon","flag")),
        EmojiItem("🇨🇳", listOf("china","chinese","flag")),
        EmojiItem("🇮🇳", listOf("india","indian","flag")),
        EmojiItem("🇧🇷", listOf("brazil","brazilian","flag")),
        EmojiItem("🇰🇷", listOf("korea","korean","south korea","flag")),
        EmojiItem("🇨🇦", listOf("canada","canadian","maple","flag")),
        EmojiItem("🇦🇺", listOf("australia","australian","flag")),
        EmojiItem("🇮🇹", listOf("italy","italian","flag")),
        EmojiItem("🇪🇸", listOf("spain","spanish","flag")),
        EmojiItem("🇲🇽", listOf("mexico","mexican","flag")),
        EmojiItem("🇿🇦", listOf("south africa","flag")),
        EmojiItem("🇸🇦", listOf("saudi arabia","arab","flag")),
        EmojiItem("🇦🇪", listOf("uae","emirates","dubai","flag")),
        EmojiItem("🇹🇷", listOf("turkey","turkish","flag")),
        EmojiItem("🇵🇱", listOf("poland","polish","flag")),
        EmojiItem("🇳🇱", listOf("netherlands","dutch","holland","flag")),
        EmojiItem("🇸🇪", listOf("sweden","swedish","flag")),
        EmojiItem("🇳🇴", listOf("norway","norwegian","flag")),
        EmojiItem("🇺🇦", listOf("ukraine","ukrainian","flag")),
        EmojiItem("🇵🇹", listOf("portugal","portuguese","flag")),
        EmojiItem("🇦🇷", listOf("argentina","argentinian","flag")),
        EmojiItem("🇨🇱", listOf("chile","chilean","flag")),
        EmojiItem("🇨🇴", listOf("colombia","colombian","flag")),
        EmojiItem("🇮🇩", listOf("indonesia","indonesian","flag")),
        EmojiItem("🇵🇭", listOf("philippines","filipino","flag")),
        EmojiItem("🇳🇬", listOf("nigeria","nigerian","flag")),
        EmojiItem("🇪🇬", listOf("egypt","egyptian","flag")),
        EmojiItem("🇮🇷", listOf("iran","persian","flag")),
        EmojiItem("🇵🇰", listOf("pakistan","pakistani","flag")),
        EmojiItem("🇧🇩", listOf("bangladesh","bangladeshi","flag")),
        EmojiItem("🇻🇳", listOf("vietnam","vietnamese","flag")),
        EmojiItem("🇹🇭", listOf("thailand","thai","flag")),
        EmojiItem("🇲🇾", listOf("malaysia","malaysian","flag")),
        EmojiItem("🇸🇬", listOf("singapore","singaporean","flag")),
        EmojiItem("🇨🇭", listOf("switzerland","swiss","flag","neutral")),
        EmojiItem("🇦🇹", listOf("austria","austrian","flag")),
        EmojiItem("🇧🇪", listOf("belgium","belgian","flag")),
        EmojiItem("🇬🇷", listOf("greece","greek","flag")),
        EmojiItem("🇨🇿", listOf("czech republic","czechia","flag")),
        EmojiItem("🇷🇴", listOf("romania","romanian","flag")),
        EmojiItem("🇭🇺", listOf("hungary","hungarian","flag")),
        EmojiItem("🇫🇮", listOf("finland","finnish","flag")),
        EmojiItem("🇩🇰", listOf("denmark","danish","flag")),
        EmojiItem("🇮🇱", listOf("israel","israeli","flag")),
        EmojiItem("🇸🇰", listOf("slovakia","slovak","flag")),
        EmojiItem("🇭🇷", listOf("croatia","croatian","flag")),
        EmojiItem("🇷🇸", listOf("serbia","serbian","flag")),
        EmojiItem("🇧🇬", listOf("bulgaria","bulgarian","flag")),
        EmojiItem("🇰🇿", listOf("kazakhstan","kazakh","flag")),
        EmojiItem("🇺🇿", listOf("uzbekistan","uzbek","flag")),
    )),
)

fun searchEmoji(query: String): List<EmojiItem> {
    if (query.isBlank()) return emptyList()
    val q = query.trim().lowercase()
    return EMOJI_CATEGORIES
        .flatMap { it.items }
        .filter { item -> item.keywords.any { kw -> kw.contains(q) } || item.emoji.contains(q) }
        .distinctBy { it.emoji }
        .take(60)
}
